### ISSUE TITLE
(PRIORITY) SRCFPlugin email improvements

### ISSUE THREAD

**Issue by jsyiek** [jsyiek/AU2#38]
There were some poor design choices made in my development of the email plugin that weren't obvious at the time. Could someone pick up these fixes:
1) (must) allow selective emailing of specific assassins 
2) (must) don't email dead assassins
3) (must) don't HTML escape emails
4) (must) upload databases when sending emails
5) (wish) selective emailing of police

**Comment by NerdyNinja11** [comment]
Could also selectively email those who have just become wanted/inco as a warning, since this is not always immediately obvious to players.

**Comment by jsyiek** [comment]
Great point. I think this should change the CompetencyPlugin to emit a "must email" signal when it detects someone's competency period has lapsed (but only once).
