### ISSUE TITLE
Pseudonyms not rendering correctly on death if later pseudonym added

### ISSUE THREAD

**Issue by jsyiek** [jsyiek/AU2#4]
Steps to reproduce:
- Add an assassin
- Add an event with their death
- Add another pseudonym to that assassin

**Comment by thenewtonium** [comment]
So, to clarify, the bug here is that [DX] renders the later pseudonym as well?

**Comment by jsyiek** [comment]
Yup. The cause comes down in part to AU2's design philosophy. AU1 would update the state throughout the game, meaning bugs that cause the state to be incorrectly stored or make the state inconsistent would halt the game (e.g., the targeting graph is stored in full, preventing the annulment of a kill). AU2 attempted to rectify this by trying to avoid storing this derived state and only storing the starting points from where it could be regenerated later. 

To this end, events don't store the pseudonyms you had at the time (in case you change them later or when the event occurred). A simple solution at first seems like it could be just to store the pseudonyms the assassins had (or how many, etc.) but it introduces issues if the umpire goes to update the event/assassin later and could lead to inconsistency (e.g., storing a pseudonym becomes inconsistent if the umpire later edits it).

I'm unsure how to fix this other than making a changelog to each assassin's pseudonym list in `Assassin` and using event datetime to determine which pseudonyms existed at death time. I'm not necessarily a big fan of this solution. For one, it would need to come with an appropriate setter method for `pseudonyms` so that future plugins that want to add/edit/delete/etc. pseudonyms on their own and not through `CorePlugin` correctly update the change log. 

It's not simple and only occurs in May Week and in niche cases with police officers who die far too many times (rare).

**Comment by thenewtonium** [comment]
What is the issue with storing the number of pseudonyms a player had at the time? It's no less consistent than the way the main pseudonym is stored, surely?

**Comment by jsyiek** [comment]
Yeah, part of the reason this issue has sat open for a long time is every solution I've thought up has some weird edge case that violates state consistency requirements that could plausibly be committed by an umpire within the next 15 years.
