### ISSUE TITLE
PgUp and PgDown support

### ISSUE THREAD

**Issue by NerdyNinja11** [jsyiek/AU2#75]
Not sure if pyinquirer supports this, but support for the PgUp and PgDown keys (Home and End as well?) would be nice for quickly traversing long lists of options

**Comment by thenewtonium** [comment]
Looks like it it shouldn't be too difficult to override `inquirer.render.console._list.List.process_input` with a wrapper that handles PgUp and PgDown; the code for Up and Down just sets an index so it shouldn't be too hard to implement (famous last words...)

**Comment by thenewtonium** [comment]
(Ditto for `inquirer.render.console._checkbox.Checkbox.process_input`; reading which I have discovered that you can use <kbd>Ctrl</kbd>+<kbd>A</kbd> to select all,  <kbd>Ctrl</kbd>+<kbd>R</kbd> to deselect all, qn  <kbd>Ctrl</kbd>+<kbd>I</kbd> to invert your choice.)
