### ISSUE TITLE
Reports need to respect newlines

### ISSUE THREAD

**Issue by NerdyNinja11** [jsyiek/AU2#89]
Reports currently don't respect paragraphs/newlines unless html <br> tags are used.

This leads to walls of text being posted by the vast majority of players who aren't intimately familier with AU, which is really bad for readability.

This needs to be fixed for reports without that are not prefixed with

**Comment by jsyiek** [comment]
This can be done with a sanity check - look for `\n` in a string and ask the umpire if they want to enable HTML for the report and then repalce them with `<br>` 

(One risk here is that sanity checks looking for other HTML features won't double check it! but I reckon it's probably worth it, sanity checks are best effort)

**Comment by NerdyNinja11** [comment]
I'm not sure I like this solution, since an umpire not confident with HTML could be confused when editing a normal report suddenly shows a bunch of html. 
Could the report generating code just respect \n in the initial report and change it when the page is generated? 
(it's definitely not clean, but for usubility, since no-html is the default and theoretically never needs to be used, it seems to make more sense)

**Comment by jsyiek** [comment]
That could work!
